trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerCompose@0 # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops
  inputs:
    action: 'Build services'
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Naos 22463ad3-c6d2-4e7e-911d-c50474250fa0'
    # azureContainerRegistry: '{"loginServer":"naossample.azurecr.io", "id" : "/subscriptions/22463ad3-c6d2-4e7e-911d-c50474250fa0/resourceGroups/naos/providers/Microsoft.ContainerRegistry/registries/naossample"}'
    dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
    additionalDockerComposeFiles: '$(System.DefaultWorkingDirectory)/docker-compose.override.yml'
    includeLatestTag: true

- task: DockerCompose@0 # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops
  inputs:
    action: 'Push services'
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Naos 22463ad3-c6d2-4e7e-911d-c50474250fa0'
    azureContainerRegistry: '{"loginServer":"naossample.azurecr.io", "id" : "/subscriptions/22463ad3-c6d2-4e7e-911d-c50474250fa0/resourceGroups/naos/providers/Microsoft.ContainerRegistry/registries/naossample"}'
    dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
    additionalDockerComposeFiles: '$(System.DefaultWorkingDirectory)/docker-compose.override.yml'
    includeLatestTag: true