version: '3.4'

services:
  apigateway.application.web:
    image: ${REGISTRY:-naos}/apigateway.application.web:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - 80:80

  customers.application.web:
    image: ${REGISTRY:-naos}/customers.application.web:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - 80:80

  orders.application.web:
    image: ${REGISTRY:-naos}/orders.application.web:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - 80:80