version: '3.4'

services:
  naos.sample.apigateway.application.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5100
    ports:
      - 5000:80
      - 5100:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - naos

  naos.sample.customers.application.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - 5002:80 # The API Gateway redirects and access through the internal port (80)
                # In a production environment the external port (5002) should be removed, kept here for microservice debugging purposes
    networks:
      - naos

  naos.sample.orders.application.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - 5006:80 # The API Gateway redirects and access through the internal port (80)
                # In a production environment the external port (5006) should be removed, kept here for microservice debugging purposes
    networks:
      - naos

networks:
  naos:
    external: true
