apps:
  - name: api
    script: dotnet Naos.Sample.Application.WebGateway.dll
    cwd: ../Naos.Sample.Application.WebGateway/src/Naos.Sample.Application.WebGateway/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5000
  - name: availability
    script: dotnet Naos.Sample.Availability.Application.Web.dll
    cwd: ../Naos.Sample.Availability/src/Naos.Sample.Availability.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5001
  - name: customers
    script: dotnet Naos.Sample.Customers.Application.Web.dll
    cwd: ../Naos.Sample.Customers/src/Naos.Sample.Customers.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5002
  - name: deliveries
    script: dotnet Naos.Sample.Deliveries.Application.Web.dll
    cwd: ../Naos.Sample.Deliveries/src/Naos.Sample.Deliveries.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5003
  - name: identity
    script: dotnet Naos.Sample.Identity.Application.Web.dll
    cwd: ../Naos.Sample.Identity/src/Naos.Sample.Identity.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5004
  - name: operations
    script: dotnet Naos.Sample.Operations.Application.Web.dll
    cwd: ../Naos.Sample.Operations/src/Naos.Sample.Operations.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5005
  - name: orders
    script: dotnet Naos.Sample.Orders.Application.Web.dll
    cwd: ../Naos.Sample.Orders/src/Naos.Sample.Orders.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5006
  - name: parcels
    script: dotnet Naos.Sample.Parcels.Application.Web.dll
    cwd: ../Naos.Sample.Parcels/src/Naos.Sample.Parcels.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5007
  - name: pricing
    script: dotnet Naos.Sample.Pricing.Application.Web.dll
    cwd: ../Naos.Sample.Pricing/src/Naos.Sample.Pricing.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5008
  - name: vehicles
    script: dotnet Naos.Sample.Vehicles.Application.Web.dll
    cwd: ../Naos.Sample.Vehicles/src/Naos.Sample.Vehicles.Application.Web/bin/release/netcoreapp2.2/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5009
