version: '3.5'

services:
  customers-service:
    image: naos/naos.sample.services.customers
    container_name: customers-service
#    restart: unless-stopped
#    restart: always
    ports:
      - 5002:5000
    networks:
      - naos

  orders-service:
    image: naos/naos.sample.services.orders
    container_name: orders-service
#    restart: unless-stopped
#    restart: always
    ports:
      - 5006:5000
    networks:
      - naos

networks:
  naos:
    external: true